[package]
name = "image-builder"
version = "0.4.0"
edition = "2021"
description = "A tool for mount images with texts"
license = "MIT"

[dependencies]
image = "0.24.5"
imageproc = "0.23.0"
rusttype = "0.9.3"
